from velait.common.exceptions import VelaitError


class RequestError(VelaitError):
    pass
